### ISSUE TITLE
readelf display not in english

### ISSUE THREAD

**Issue by lprat** [OfriOuzan/HardeningMeter#1]
Hi,
Thank you for your tool.

Just a note, I tried your tool, and my default language on Linux is not English. When I run your code the string doesn't match in return of readelf command, I need to add "LC_ALL=C" before calling your script for it to work.

Perhaps add this information to your Readme file.

Thanks.
lionel

**Comment by OfriOuzan** [comment]
Hi,

Thanks for the note!
I added it to the Readme file.

Ofri
